version: '3.4'
services:
  substrate-telemetry-archipel.public.dappnode.eth:
    build: ./build
    image: 'substrate-telemetry-archipel.public.dappnode.eth:0.1.0'
    ports:
      - '3000:3000'
      - '8000:8000'
    environment:
      - REMOTE_PUBLIC_IP_TELEMETRY_BACKEND=
    restart: always
