version: '3.4'
services:
  substrate-telemetry-archipel.public.dappnode.eth:
    build: ./build
    image: 'substrate-telemetry-archipel.public.dappnode.eth:0.0.1'
    ports:
      - '3000:3000'
    restart: always